
CREATE TABLE todo (
    Id INTEGER NOT NULL AUTO_INCREMENT,
    Task VARCHAR(255) NOT NULL,
    PRIMARY KEY (Id)
);

CREATE USER 'todouser'@'localhost' IDENTIFIED BY 'todouser2022';
GRANT ALL PRIVILEGES ON TodoListDB.* TO 'todouser'@'localhost';
FLUSH PRIVILEGES;